# Generated by Django 5.2.4 on 2025-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('matric_no', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=15)),
                ('rfid_uid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
