# Generated by Django 5.2.4 on 2025-07-16 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_courseregistration_weeklylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklylog',
            name='date',
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
